//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cush.Windows.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cush.Windows.Services.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find existing service in registry..
        /// </summary>
        internal static string EXCEPTION_CannotFindServiceInRegistry {
            get {
                return ResourceManager.GetString("EXCEPTION_CannotFindServiceInRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTION: {0}.
        /// </summary>
        internal static string EXCEPTION_HeaderWithMessage {
            get {
                return ResourceManager.GetString("EXCEPTION_HeaderWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWindowsService cannot be null in call to WindowsServiceHarness.GetInstance()..
        /// </summary>
        internal static string EXCEPTION_IWindowsServiceCannotBeNull {
            get {
                return ResourceManager.GetString("EXCEPTION_IWindowsServiceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types deriving from the WindowsService class must be decorated with a WindowsServiceAttribute..
        /// </summary>
        internal static string EXCEPTION_ServiceMustBeMarkedWithAttribute {
            get {
                return ResourceManager.GetString("EXCEPTION_ServiceMustBeMarkedWithAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string INFO_Done {
            get {
                return ResourceManager.GetString("INFO_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Client: Email Sent..
        /// </summary>
        internal static string INFO_EmailSent {
            get {
                return ResourceManager.GetString("INFO_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;{0}&apos; service...  .
        /// </summary>
        internal static string INFO_InstallingWindowsService {
            get {
                return ResourceManager.GetString("INFO_InstallingWindowsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service is already running..
        /// </summary>
        internal static string INFO_ServiceAlreadyRunning {
            get {
                return ResourceManager.GetString("INFO_ServiceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service is not started..
        /// </summary>
        internal static string INFO_ServiceNotStarted {
            get {
                return ResourceManager.GetString("INFO_ServiceNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} service is {1}..
        /// </summary>
        internal static string INFO_ServiceStatus {
            get {
                return ResourceManager.GetString("INFO_ServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service {0} as a background service.  .
        /// </summary>
        internal static string INFO_StartingBackgroundService {
            get {
                return ResourceManager.GetString("INFO_StartingBackgroundService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0} service...  .
        /// </summary>
        internal static string INFO_StartingService {
            get {
                return ResourceManager.GetString("INFO_StartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping {0} service...  .
        /// </summary>
        internal static string INFO_StoppingService {
            get {
                return ResourceManager.GetString("INFO_StoppingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling &apos;{0}&apos; service...  .
        /// </summary>
        internal static string INFO_UninstallingWindowsService {
            get {
                return ResourceManager.GetString("INFO_UninstallingWindowsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string Noun_NoKey {
            get {
                return ResourceManager.GetString("Noun_NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Noun_YesKey {
            get {
                return ResourceManager.GetString("Noun_YesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot stop service..
        /// </summary>
        internal static string WARN_CannotStopService {
            get {
                return ResourceManager.GetString("WARN_CannotStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install this version anyway [{0}/{1}]?  .
        /// </summary>
        internal static string Warn_InstallAnyway {
            get {
                return ResourceManager.GetString("Warn_InstallAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed version is newer..
        /// </summary>
        internal static string Warn_InstalledVersionIsNewer {
            get {
                return ResourceManager.GetString("Warn_InstalledVersionIsNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service is already installed..
        /// </summary>
        internal static string WARN_ServiceAlreadyInstalled {
            get {
                return ResourceManager.GetString("WARN_ServiceAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service is not installed..
        /// </summary>
        internal static string WARN_ServiceNotInstalled {
            get {
                return ResourceManager.GetString("WARN_ServiceNotInstalled", resourceCulture);
            }
        }
    }
}
