//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cush.TestHarness.WPF.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cush.TestHarness.WPF.Views.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string BUTTON_Apply {
            get {
                return ResourceManager.GetString("BUTTON_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BUTTON_Cancel {
            get {
                return ResourceManager.GetString("BUTTON_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Recent Files now!.
        /// </summary>
        public static string BUTTON_ClearFilesNow {
            get {
                return ResourceManager.GetString("BUTTON_ClearFilesNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About .
        /// </summary>
        public static string HEADER_About {
            get {
                return ResourceManager.GetString("HEADER_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        public static string HEADER_ConfirmPassword {
            get {
                return ResourceManager.GetString("HEADER_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        public static string HEADER_CopyrightVersion {
            get {
                return ResourceManager.GetString("HEADER_CopyrightVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password to log in:.
        /// </summary>
        public static string HEADER_EnterPassword {
            get {
                return ResourceManager.GetString("HEADER_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Font family:.
        /// </summary>
        public static string HEADER_FontFamily {
            get {
                return ResourceManager.GetString("HEADER_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string HEADER_General {
            get {
                return ResourceManager.GetString("HEADER_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Password:.
        /// </summary>
        public static string HEADER_LoginPassword {
            get {
                return ResourceManager.GetString("HEADER_LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview:.
        /// </summary>
        public static string HEADER_Preview {
            get {
                return ResourceManager.GetString("HEADER_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string HEADER_Privacy {
            get {
                return ResourceManager.GetString("HEADER_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Size:.
        /// </summary>
        public static string HEADER_Size {
            get {
                return ResourceManager.GetString("HEADER_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Password:.
        /// </summary>
        public static string HEADER_UnlockPassword {
            get {
                return ResourceManager.GetString("HEADER_UnlockPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (simulated).
        /// </summary>
        public static string SimulatedText {
            get {
                return ResourceManager.GetString("SimulatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string TEXT_AllRightsReserved {
            get {
                return ResourceManager.GetString("TEXT_AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TEXT_ApplicationDescription {
            get {
                return ResourceManager.GetString("TEXT_ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Name.
        /// </summary>
        public static string TEXT_ApplicationName {
            get {
                return ResourceManager.GetString("TEXT_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string TEXT_Bold {
            get {
                return ResourceManager.GetString("TEXT_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law..
        /// </summary>
        public static string TEXT_CopyrightWarning {
            get {
                return ResourceManager.GetString("TEXT_CopyrightWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Mode.
        /// </summary>
        public static string TEXT_DebugMode {
            get {
                return ResourceManager.GetString("TEXT_DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes to {0}?.
        /// </summary>
        public static string TEXT_DoYouWantToSave {
            get {
                return ResourceManager.GetString("TEXT_DoYouWantToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Password Protection.
        /// </summary>
        public static string TEXT_EditorPasswordProtection {
            get {
                return ResourceManager.GetString("TEXT_EditorPasswordProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Password Protection.
        /// </summary>
        public static string TEXT_EnablePasswordProtection {
            get {
                return ResourceManager.GetString("TEXT_EnablePasswordProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string TEXT_File {
            get {
                return ResourceManager.GetString("TEXT_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Password Protection.
        /// </summary>
        public static string TEXT_FilePasswordProtection {
            get {
                return ResourceManager.GetString("TEXT_FilePasswordProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Font.
        /// </summary>
        public static string TEXT_Font {
            get {
                return ResourceManager.GetString("TEXT_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        public static string TEXT_Fonts {
            get {
                return ResourceManager.GetString("TEXT_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string TEXT_General {
            get {
                return ResourceManager.GetString("TEXT_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string TEXT_Italic {
            get {
                return ResourceManager.GetString("TEXT_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN OTHER FILES.
        /// </summary>
        public static string TEXT_OpenOtherFiles {
            get {
                return ResourceManager.GetString("TEXT_OpenOtherFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick brown fox jumps over the lazy dog..
        /// </summary>
        public static string TEXT_Preview {
            get {
                return ResourceManager.GetString("TEXT_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string TEXT_RecentFiles {
            get {
                return ResourceManager.GetString("TEXT_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string TEXT_Settings {
            get {
                return ResourceManager.GetString("TEXT_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep a list of recently opened files in the File menu..
        /// </summary>
        public static string TEXT_ShowRecentFiles {
            get {
                return ResourceManager.GetString("TEXT_ShowRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Splash Screen.
        /// </summary>
        public static string TEXT_ShowSplashScreen {
            get {
                return ResourceManager.GetString("TEXT_ShowSplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tooltips.
        /// </summary>
        public static string TEXT_ShowTooltips {
            get {
                return ResourceManager.GetString("TEXT_ShowTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Similar Activity Handling.
        /// </summary>
        public static string TEXT_SimilarActivity {
            get {
                return ResourceManager.GetString("TEXT_SimilarActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar Activity Handling.
        /// </summary>
        public static string TEXT_SimilarActivityHandling {
            get {
                return ResourceManager.GetString("TEXT_SimilarActivityHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string TEXT_Theme {
            get {
                return ResourceManager.GetString("TEXT_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About &quot;App Name&quot;.
        /// </summary>
        public static string TOOLTIP_About {
            get {
                return ResourceManager.GetString("TOOLTIP_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Menu.
        /// </summary>
        public static string TOOLTIP_File {
            get {
                return ResourceManager.GetString("TOOLTIP_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to open file.
        /// </summary>
        public static string TOOLTIP_ReturnToOpenFile {
            get {
                return ResourceManager.GetString("TOOLTIP_ReturnToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Settings.
        /// </summary>
        public static string TOOLTIP_Settings {
            get {
                return ResourceManager.GetString("TOOLTIP_Settings", resourceCulture);
            }
        }
    }
}
