//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cush.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cush.Common.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of {0} is already running..
        /// </summary>
        public static string Error_AnotherInstanceRunning {
            get {
                return ResourceManager.GetString("Error_AnotherInstanceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity must be at least the length of the initial array..
        /// </summary>
        public static string EXCEPTION_CapacityMustBeAtLeastAsLongAsArray {
            get {
                return ResourceManager.GetString("EXCEPTION_CapacityMustBeAtLeastAsLongAsArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity must be at least one..
        /// </summary>
        public static string EXCEPTION_CapacityMustBeAtLeastOne {
            get {
                return ResourceManager.GetString("EXCEPTION_CapacityMustBeAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration failed version..
        /// </summary>
        public static string EXCEPTION_EnumerationFailedVersion {
            get {
                return ResourceManager.GetString("EXCEPTION_EnumerationFailedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration operation cannot happen..
        /// </summary>
        public static string EXCEPTION_EnumerationOperationCannotHappen {
            get {
                return ResourceManager.GetString("EXCEPTION_EnumerationOperationCannotHappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key cannot be null..
        /// </summary>
        public static string EXCEPTION_KeyCannotBeNull {
            get {
                return ResourceManager.GetString("EXCEPTION_KeyCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already running.
        /// </summary>
        public static string Header_AnotherInstanceRunning {
            get {
                return ResourceManager.GetString("Header_AnotherInstanceRunning", resourceCulture);
            }
        }
    }
}
